### ISSUE TITLE
Script Errors out when trying to create IMDb top 250

### ISSUE THREAD

**Issue by goku-son** [pbrink231/plex_top_playlists#20]
I am running this script on a Windows 10 system so not sure if that is the issue. 

I had to add make the following changes to the script because it would error out almost immediately:

#from plexapi.utils import NA
NA=""

With the above changes, the script progresses but when it gets to the IMDB section it errors out with:

Retrieving the IMDB Top 250 list...
Traceback (most recent call last):
  File "C:\JBOPS-master\fun\plex_playlist_update.py", line 374, in <module>
    list_updater()
  File "C:\JBOPS-master\fun\plex_playlist_update.py", line 365, in list_updater
    run_movies_lists(plex)
  File "C:\JBOPS-master\fun\plex_playlist_update.py", line 303, in run_movies_lists
    imdb_top_movies_ids = imdb_top_imdb_id_list(IMDB_CHART_URL)
  File "C:\JBOPS-master\fun\plex_playlist_update.py", line 262, in imdb_top_imdb_id_list
    tree = parse(list_url)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 940, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src\lxml\etree.pyx", line 3426, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 638, in lxml.etree._raiseParseError
IOError: Error reading file 'http://www.imdb.com/chart/top': failed to load external entity "http://www.imdb.com/chart/top"

Any idea what I may be doing wrong? Thanks in advance.

**Comment by goku-son** [comment]
Issue was resolved with the workaround documented in issue #17.
