### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by skius** [pbrink231/plex_top_playlists#3]
Running the script I get this error:

```===================================================================
   Automated Playlist to Plex script
===================================================================

Retrieving a list of movies from the 'Movies' library in Plex...
Retrieving new lists
Retrieving the Trakt weekly list...
Traceback (most recent call last):
  File "./plex_playlist_update.py", line 302, in <module>
    list_updater()
  File "./plex_playlist_update.py", line 293, in list_updater
    run_movies_lists(plex)
  File "./plex_playlist_update.py", line 256, in run_movies_lists
    trakt_weekly_imdb_ids = trakt_watched_imdb_id_list()
  File "./plex_playlist_update.py", line 167, in trakt_watched_imdb_id_list
    response = urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden```

PS: I had to install the 'xmltodict' module

**Comment by skius** [comment]
Okay, I seem to have fixed this by adding my Trakt API key to the header of the Trakt requests.

**Comment by pbrink231** [comment]
I took out the key because it seemed to work without it.  I will put it back in.  Was hoping i didn't need it for none user specific query like i have.

**Comment by pbrink231** [comment]
I have added the Trakt API information back in.  Found that it has to be in the call but the key can be blank for the information i am retrieving.  No longer need to grab an API key from Trakt.
