### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by skinnyzaz** [pbrink231/plex_top_playlists#31]
I am getting a timeout issue, I tried changing the timeout in the settings.ini but it didnt help.

getting imdb ids from url: https://www.imdb.com/chart/top
IMDB Top 250 Example: STARTING PLAYLIST - TYPE: chart - URL: https://www.imdb.com/chart/top - KIND: collection
IMDB Top 250 Example: finding matching movies for playlist with count 250
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./plex_playlist_update.py", line 631, in <module>
    list_updater(plex)
  File "./plex_playlist_update.py", line 595, in list_updater
    run_movies_lists(plex, users)
  File "./plex_playlist_update.py", line 480, in run_movies_lists
    imdb_list_loop(plex, shared_users, movie_id_dict)
  File "./plex_playlist_update.py", line 445, in imdb_list_loop
    setup_movie_playlist(plex, shared_users, ids, movie_id_dict, title, kind, show_summary)
  File "./plex_playlist_update.py", line 270, in setup_movie_playlist
    add_items_to_collection(plex, summary.matching_movies, summary.name)
  File "./plex_playlist_update.py", line 254, in add_items_to_collection
    media.addCollection(tag)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/base.py", line 371, in addCollection
    self._edit_tags('collection', collections)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/base.py", line 363, in _edit_tags
    self.refresh()
  File "/usr/local/lib/python3.5/dist-packages/plexapi/base.py", line 409, in refresh
    self._server.query(key, method=self._server._session.put)
  File "/usr/local/lib/python3.5/dist-packages/plexapi/server.py", line 397, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=32400): Read timed out. (read timeout=30)

**Comment by pbrink231** [comment]
This looks like you are getting a timeout issues on your connection to plex.  Your plex is up and running? and your running this script from the same computer your plex is on?

it is trying to connect to localhost:32400

**Comment by pbrink231** [comment]
Please let me know if this is still an issue.  Going to close it for now.  Also please use the develop branch to test `git checkout develop`
